language: ruby

rvm:
  - 2.1.3
  - 2.3.0
  - 2.4.0
  - 2.5.0

env:
  # https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
  - RAILS_ENV=test

services:
  - docker
  - redis

before_install:
  - "gem update --system"
  - "gem pristine bundler"

before_script:
  - cp config/database.yml.sample config/database.yml

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rspec spec/models
  - RAILS_ENV=test bundle exec rspec spec/features
  - RAILS_ENV=test bundle exec rspec spec/workers

env:
 - RAILS_ENV=test
