language: ruby
rvm:
  - 2.1.3
  - 2.3.0
branches:
  only:
    - master
    - development
before_script:
  - cp config/database.yml.sample config/database.yml

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

env:
 - RAILS_ENV=test
