default: &default
  :service: 'redis://localhost:6379'
  :logfile: ./log/sidekiq.log
  :queues:
  - moderation

development:
  <<: *default

test:
  <<: *default

qa:
  <<: *default

production:
  :service: ENV['REDISTOGO_URL']
  :queues:
  - moderation

