---
:verbose: true
:concurrency: 5
:timeout: 30
:queues:
  - moderation

production:
  :service: ""

development:
  :service: 'redis://localhost:6379'
  :logfile: ./log/sidekiq.log

test:
  :service: 'redis://localhost:6379'
  :logfile: ./log/sidekiq.log

